---

- block:
  - name: Create monitoring namespace
    kubernetes.core.k8s:
      name: monitoring
      api_version: v1
      kind: Namespace
      state: present
      kubeconfig: '../generated_configuration/kubeconfig'

  - name: Enable istio auto injection in namespace
    kubernetes.core.k8s:
      state: patched
      kind: Namespace
      name: monitoring
      kubeconfig: '../generated_configuration/kubeconfig'
      definition:
        metadata:
          labels:
            istio-injection: disabled
    when:
      - istio.enabled | bool
      - istio.ingress | bool

  - include_tasks:
      file: loki_grafana.yaml
      apply:
        tags:
          - loki
          - grafana
    tags:
      - loki
      - grafana

  - include_tasks:
      file: kiali.yaml
      apply:
        tags: kiali
    when:
      - monitoring.kiali.enabled | bool
      - istio.enabled | bool
      - istio.ingress | bool
    tags:
      - kiali

  - name: Deploy Virtual Services
    kubernetes.core.k8s:
      src: ../generated_configuration/monitoring_virtual_service.yaml
      namespace: monitoring
      state: present
      kubeconfig: '../generated_configuration/kubeconfig'
    when:
      - istio.enabled | bool
      - istio.ingress | bool
  when: monitoring.loki_grafana.enabled | bool

