---

istio:
  enabled: false
  ingress: false

monitoring:
  domain: ''
  loki_grafana:
    enabled: true
    chart_version: 2.6.1
    basepath: /system/grafana
  kiali:
    enabled: true
    chart_version: 1.48.0
    auth:
      strategy: token