---

- name: Add jetstack repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Create cert-manager namespace
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    definition:
      metadata:
        labels:
          istio-injection: disabled
    state: present
    kubeconfig: '../generated_configuration/kubeconfig'

- name: Install Cert Manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "{{ cert_manager.chart_version if cert_manager.get('chart_version') else chart_version }}"
    release_namespace: cert-manager
    values:
      installCRDs: true
    kubeconfig: '../generated_configuration/kubeconfig'
  retries: 3
  delay: 15
