---

- include: deploy.yaml

- include_tasks: certificates/main.yaml
  when: >
    istio.ingress | bool and 
    (istio.internal_gateway.secure.enabled | bool or 
    istio.external_gateway.secure.enabled | bool)

- include_tasks: gateway.yaml
  when: istio.ingress | bool
