---

- name: Check if any internal hosts require creating new self-signed certificates
  set_fact:
    internal_self_signed_creation: true
  when: item.create_self_signed_certificate | bool
  with_items: "{{ istio.internal_gateway.secure.tls.hosts }}"

- name: Check if any external hosts require creating new self-signed certificates
  set_fact:
    external_self_signed_creation: true
  when: item.create_self_signed_certificate | bool
  with_items: "{{ istio.external_gateway.secure.tls.hosts }}"

- include_tasks: internal/self_signed.yaml
  when:
    - internal_self_signed_creation | bool
    - cert_manager.ca.enabled | bool

- include_tasks: internal/custom.yaml

- include_tasks: external/self_signed.yaml
  when:
    - external_self_signed_creation | bool
    - cert_manager.ca.enabled | bool

- include_tasks: external/custom.yaml