---

- name: "Deploy K0S Cluster"
  hosts: localhost
  gather_facts: no
  vars:
    ansible_host_key_checking: false
  vars_files:
    - vaults/vault.yaml
  remote_user: "{{ host.vm_user }}"
  roles:
    - { role: 'terraform', task: 'deploy' }
    - { role: 'ha', when: (vm_output.outputs.lb_ip_addresses.value | length > 0) }
    - { role: 'k0s' }
    - { role: 'istio', when: (istio.enabled | bool) }
    - { role: 'monitoring', when: (monitoring.enabled | bool) }
    - { role: 'hello-kate', when: (test_app.enabled | bool) }
