---

- name: "Destroy K0S Cluster"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Include vault variables
      include_vars: vaults/vault.yaml

    - name: "Generate tfvars file for Terraform"
      blockinfile:
        path: ../terraform/input.tfvars
        create: yes
        block: |
          vsphere_server = "{{ vcenter.host }}"
          vsphere_username = "{{ vcenter.username }}"
          vsphere_password = "{{ vcenter.password }}"
          datacenter = "{{ vcenter.datacenter }}"
          resource_pool = "{{ vcenter.resource_pool }}"
          cluster = "{{ vcenter.cluster }}"
          cp_vm_params = {
            hostname = "{{ host.controlplane.hostname }}"
            domain = "{{ host.controlplane.domain }}"
            vcpu = "{{ host.controlplane.vcpu }}"
            ram = "{{ host.controlplane.ram }}"
            disk_datastore = "{{ host.controlplane.disk_datastore }}"
            disk_size = "{{ host.controlplane.disk_size }}"
            network_name = "{{ host.controlplane.network_name }}"
          }
          worker_vm_params = {
            hostname = "{{ host.worker.hostname }}"
            domain = "{{ host.worker.domain }}"
            vcpu = "{{ host.worker.vcpu }}"
            ram = "{{ host.worker.ram }}"
            disk_datastore = "{{ host.worker.disk_datastore }}"
            disk_size = "{{ host.worker.disk_size }}"
            network_name = "{{ host.worker.network_name }}"
          }
          lb_vm_params = {
            hostname = "{{ host.lb.hostname }}"
            domain = "{{ host.lb.domain }}"
            vcpu = "{{ host.lb.vcpu }}"
            ram = "{{ host.lb.ram }}"
            disk_datastore = "{{ host.lb.disk_datastore }}"
            disk_size = "{{ host.lb.disk_size }}"
            network_name = "{{ host.lb.network_name }}"
          }
          template_properties = {
            "public-keys" = "{{ host.ssh_public_key }}"
          }
          cp_vm_count = "{{ kubernetes.controlplane.count }}"
          worker_vm_count = "{{ kubernetes.worker.count }}"

    - name: "Delete VM's"
      community.general.terraform:
        project_path: "../terraform/"
        state: absent
        force_init: yes
        variables_file:
          - input.tfvars
      delegate_to: localhost
      register: terraform_output

    - name: "Delete files"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - '../terraform/input.tfvars'
        - '../k0sctl.yaml'
        - '../kubeconfig'
      delegate_to: localhost
      failed_when: no